In [3]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) #배열의 크기
print(array.dtype) #배열 원소의 타입
print(array[2]) #인덱스 2의 원소


3
int32
3


In [8]:
import numpy as np
#0부터 3까지의 배열
array1 = np.arange(4)
print(array1)
#0으로 초기화시킨 4 by 4의 배열(실수)
array2 = np.zeros((4, 4), dtype = float)
print(array2)
#1로 초기화시킨 3 by 3의 배열(문자)
array3 = np.ones((3, 4), dtype = str)
print(array3)
#0부터 9까지 랜덤하게 초기화된 배열
array4 = np.random.randint(0, 10, (3, 3))
print(array4)
#평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[[5 5 3]
 [3 9 1]
 [1 7 0]]
[[ 2.26266415  0.58501134  1.34265861]
 [-0.97928398 -0.00904099  0.06407755]
 [ 1.00126715  0.44196952  0.46572961]]


In [10]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2]) # 배열 합치기(열 방향)

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [11]:
import numpy as np

array1 = np.arange(4).reshape(1,4) # 1 by 4로 모양 바꾸기
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis = 0) # 행 방향으로 더하기

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [12]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape(2, 2)

print(array2.shape)
print(array2)

(2, 2)
[[1 2]
 [3 4]]


In [15]:
import numpy as np

array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis = 1) # [2]를 기준으로 좌우 나누기mport numpy as np

array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis = 1) # [2]를 기준으로 좌우 나누기

print(left.shape)
print(right.shape)
print(right[1][1])

print(left.shape)
print(right.shape)
print(right[1][1])

(2, 2)
(2, 2)
7


In [17]:
import numpy as np

array = np.random.randint(1, 9, size = 4).reshape(2, 2)
print(array)
result_array = array * 10
print(result_array)

[[3 5]
 [5 4]]
[[30 50]
 [50 40]]


In [18]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)

array3 = array1 + array2

print(array3)


[[0 2]
 [2 4]]


In [21]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4, 1)

print(array3)
print(array4)
print(array3 + array4) # 브로드캐스트 : 배열을 동적으로 사용용

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [26]:
#마스킹 연산 : 각 원소에 대한 조건 체크
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)
array2 = array1 <10
print(array2)

array1[array2] = 100 # 조건을 만족하는 원소를 100으로 변환마스킹 연산 : 각 원소에 대한 조건 체크
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)
array2 = array1 <10
print(array2)

array1[array2] = 100 # 조건을 만족하는 원소를 100으로 변환
print(array1)

print(array1)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [28]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("Max: ", np.max(array))
print("min: ", np.min(array))
print("Sum: ", np.sum(array))
print("Mean: ", np.mean(array))

print("합계:", np.sum(array, axis=0))


Max:  15
min:  0
Sum:  120
Mean:  7.5
합계: [24 28 32 36]


In [29]:
import numpy as np

#단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

#복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
no.savez('saved.npz', array1 = array1 , array2 = array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

In [32]:
import numpy as np

#Numpy 원소 정렬
array = np.array([5, 6, 2, 8, 1])
array.sort() #정렬함수mport numpy as np

print(array[::1]) # 오름차순
print(array[::-1]) # 내림차순


[1 2 5 6 8]
[8 6 5 2 1]


In [35]:
import numpy as np

#열을 기준으로 정렬
array = np.array([[1, 5, 7, 2, 3], [6, 4, 7, 5, 9]])
print(array)
array.sort(axis = 0) # 각각의 열을 비교해서 더 큰 숫자가 아래로 내려가게 됨
print(array)

[[1 5 7 2 3]
 [6 4 7 5 9]]
[[1 4 7 2 3]
 [6 5 7 5 9]]


In [43]:
import numpy as np

#균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

#난수의 재연(실행마다 결과 동일)
np.random.seed(7) # 실행결과를 일정하도록 만듦
print(np.random.randint(0, 10, (2, 3)))

#Numpy 배열 객체 복사 (array1에게는 변화가 없음)
array1 = np.arange(0, 10)
array2 = array2.copy()
array2[0] = 99
print(array1)

#중복된 원소 제거
array = np.array([1, 1, 2, 2, 3, 3, 4])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
